### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by sunlimiter** [qingmei2/MVVM-Architecture#10]
1 列表加载，首页/第二（..N）页 失败重试这个好像不容易实现
2 首页其实可以不用viewpager，navigation导航虽然会replace fragment，使用viewmdel完全可以保留数据状态，MainActivity里面BottomNavigationView 搭配NavHostFragment，然后4个子页面viewmodel使用ViewModelProviders.of(requireActivity(), viewModelFactory)创建，在fragment stop的时候记录列表状态  
`Parcelable listState = binding.recycleview.getLayoutManager().onSaveInstanceState();
 viewModel.mBundleRecyclerViewState.putParcelable(KEY_RECYCLER_STATE, listState);`
然后
 `
viewModel.pagedList.observe(this, new Observer<PagedList<ItemBean>>() {
            @Override
            public void onChanged(@Nullable PagedList<ItemBean> pagedList) {
                adapter.submitList(pagedList);
                Parcelable listState = viewModel.mBundleRecyclerViewState.getParcelable(KEY_RECYCLER_STATE);
                if (listState != null) {
                    binding.listFeed.getLayoutManager().onRestoreInstanceState(listState);
                }
            }
        });
`
切换效果很好，另外可以在MainActivity里面监听onDestinationChanged，判断是否是首页4个tab，是显示BottomNavigationView ，不是就隐藏
`navController.addOnDestinationChangedListener`

**Comment by qingmei2** [comment]
@sunlimiter 

谢谢你的建议！

> 1.列表加载，首页/第二（..N）页 失败重试这个好像不容易实现

我的理解您是在说 `PagingLibrary`的onError下重新请求的机制吧，这个其实我在另外一篇文章（[这里](https://juejin.im/post/5be7bb9f6fb9a049f069c706)）中提到了，通过RxJava的操作符就能轻松实现，和`Paging`本身反而关系不大了。

因为之前有一些朋友反馈文章中关于`RxJava`的这些操作符有一定的学习成本，因此我并没有直接放在demo中进行展示，实际上`Paging`的使用也不是demo中简单封装一下就能完成的，具体还是看实际需求哈。

> 2.关于`Navigation`的使用

非常感谢您的指导性建议，我会接下来重新研究一下这个库，并在demo中提供更优雅的示例代码！ 👍

**Comment by qingmei2** [comment]
@sunlimiter 

最近对代码进行整理和思考，关于

> 1.列表加载，首页/第二（..N）页 失败重试这个好像不容易实现

我尝试了用[这种](https://github.com/qingmei2/MVI-Rhine/blob/master/sample/src/main/java/com/github/qingmei2/sample/ui/main/home/HomeActionProcessorHolder.kt)方式将Paging的错误相关，作为事件通过 **Subject** 向ViewModel layer 传递，这种思路目前来看还是有可行性的，欢迎一起讨论哈。


--- 
此外，关于 **Navigation** 的使用优化 和 **Room** 尚未在代码中进行示例展示，是作为接下来的开发内容，因此暂时 reopen 该 issue ，也希望能对我个人有一些督促的作用（而不是close之后issue就沉掉了）😄

**Comment by bannerkun** [comment]
> 1 列表加载，首页/第二（..N）页 失败重试这个好像不容易实现
> 2 首页其实可以不用viewpager，navigation导航虽然会replace fragment，使用viewmdel完全可以保留数据状态，MainActivity里面BottomNavigationView 搭配NavHostFragment，然后4个子页面viewmodel使用ViewModelProviders.of(requireActivity(), viewModelFactory)创建，在fragment stop的时候记录列表状态
> `Parcelable listState = binding.recycleview.getLayoutManager().onSaveInstanceState(); viewModel.mBundleRecyclerViewState.putParcelable(KEY_RECYCLER_STATE, listState);`
> 然后
> `viewModel.pagedList.observe(this, new Observer<PagedList<ItemBean>>() { @Override public void onChanged(@Nullable PagedList<ItemBean> pagedList) { adapter.submitList(pagedList); Parcelable listState = viewModel.mBundleRecyclerViewState.getParcelable(KEY_RECYCLER_STATE); if (listState != null) { binding.listFeed.getLayoutManager().onRestoreInstanceState(listState); } } });`
> 切换效果很好，另外可以在MainActivity里面监听onDestinationChanged，判断是否是首页4个tab，是显示BottomNavigationView ，不是就隐藏
> `navController.addOnDestinationChangedListener`

请教大佬有demo 可以看下实现吗？

**Comment by qingmei2** [comment]
@bannerkun 

目前`Paging`的使用示例已经在项目中进行了展示；

而`Navigation`的使用可能还要等接下来的更新，你可以在[这里](https://github.com/qingmei2/MVVM-Rhine/issues/15)查看该项目的接下来的开发重点哈。

这两个库的使用教程如下,文中包含了demo的地址：

>* [Android官方架构组件Paging：分页库的设计美学](https://juejin.im/post/5c53ad9e6fb9a049eb3c5cfd)
>* [Android官方架构组件Navigation：大巧不工的Fragment管理框架](https://juejin.im/post/5c53be3951882562d27416c6)

**Comment by bannerkun** [comment]
> @bannerkun
> 
> 目前`Paging`的使用示例已经在项目中进行了展示；
> 
> 而`Navigation`的使用可能还要等接下来的更新，你可以在[这里](https://github.com/qingmei2/MVVM-Rhine/issues/15)查看该项目的接下来的开发重点哈。
> 
> 这两个库的使用教程如下,文中包含了demo的地址：
> 
> > * [Android官方架构组件Paging：分页库的设计美学](https://juejin.im/post/5c53ad9e6fb9a049eb3c5cfd)
> > * [Android官方架构组件Navigation：大巧不工的Fragment管理框架](https://juejin.im/post/5c53be3951882562d27416c6)

老哥，我主要想问导航搭配viewmodel，实现数据保留， 看那个老哥介绍的思路，不会实现，对viewmodel 不熟悉，在导航监听里根据id隐藏底部导航这个我已经实现了，最近项目都在用这个。

**Comment by qingmei2** [comment]
@bannerkun 

issue的发起者的意思是，让Activity控制一个`ViewModel`，所有的Fragment都同样持有这个`Activity`域的`ViewModel`，在Fragment被销毁和重建的时候，将数据存储在`ViewModel`中去或者从`ViewModel`中取出。

其实就是`ViewModel`的Activity和Fragment之间的通讯功能，你可以了解下 :smile:

**Comment by bannerkun** [comment]
> @bannerkun
> 
> issue的发起者的意思是，让Activity控制一个`ViewModel`，所有的Fragment都同样持有这个`Activity`域的`ViewModel`，在Fragment被销毁和重建的时候，将数据存储在`ViewModel`中去或者从`ViewModel`中取出。
> 
> 其实就是`ViewModel`的Activity和Fragment之间的通讯功能，你可以了解下 😄

多谢大佬解答，等下去了解ViewModel怎么使用。
