### ISSUE TITLE
缺少com.qingmei2.sample.databinding.FragmentLoginBinding

### ISSUE THREAD

**Issue by parsebobo** [qingmei2/MVVM-Architecture#11]
import com.qingmei2.sample.databinding_.FragmentLoginBinding

**Comment by qingmei2** [comment]
这个应该是你那边环境配置的问题，编译器没有生成FragmentLoginBinding类。

如果`DataBinding`用的不多，建议先系统学习一下`DataBinding`的使用哈。

**Comment by qingmei2** [comment]
暂未得到回复，关闭此issue，如果还有问题可以再提一个新的issue哈
