### ISSUE TITLE
（已解决）提问 绑定控件的点击事件无效

### ISSUE THREAD

**Issue by AmioLee** [qingmei2/MVVM-Architecture#12]
![111111111111111](https://user-images.githubusercontent.com/32115721/51223925-cd277680-197e-11e9-99ef-b5c51fe86a95.png)
![2222](https://user-images.githubusercontent.com/32115721/51223930-ce58a380-197e-11e9-8641-de4e2441ad25.png)
如图 怎么回事  另外大佬 可以弄个QQ群给大伙交流吗?

**Comment by qingmei2** [comment]
@AmioLee 

qq群 391638630

应该是你没有把activity注入到Binding类中，默认BaseActivity类中只注入了BR.id.activity，这样改应该就行了：

```
<data>
	<variable
		name="activity"
		type="XXXActivity" />
</data>
```

或者你在Activity里直接指定：

```kotlin
binding.delegate = this
```
