### ISSUE TITLE
可以写一些上传下载的文章吗？

### ISSUE THREAD

**Issue by bingdu0** [qingmei2/MVVM-Architecture#14]
看了你好多文章，都没有上传，和下载的文章，可以在mvvm 上实践一下吗？想学习一下

**Comment by qingmei2** [comment]
可以的，我抽空总结一篇关于app版本更新并安装的文章吧，总的来说下载本身也是异步请求，和普通的接口请求区别不大（唯一有一点意思的可能会配合一个dialog供用户操作，将这个dialog转换为一个Observable就可以了）

ps：大概会使用到 [ssseasonnn](https://github.com/ssseasonnn) 老师的 [RxDownload](https://github.com/ssseasonnn/RxDownload)这个库
