### ISSUE TITLE
关于Navigation库的疑问

### ISSUE THREAD

**Issue by jinjiafeng** [qingmei2/MVVM-Architecture#18]
用Navigation库的时候,FragmentA中会执行动画,跳转到FragmentB后回退到FragmentA,这时候动画又会重新执行,就觉得很怪,请教一下,这该怎么处理.
十分感谢~

**Comment by qingmei2** [comment]
@jinjiafeng 

最近在研究学习其他的东西，关于您描述的场景我暂时没有遇到过哈。
