### ISSUE TITLE
BaseFragment貌似有点问题

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVVM-Architecture#21]
MVVMRhine/mvvm_rhine/src/main/java/com/qingmei2/rhine/base/view/fragment/BaseFragment.kt

abstract class BaseFragment : InjectionFragment() {

    private var mRootView: View? = null

    abstract val layoutId: Int

    override fun onCreateView(inflater: LayoutInflater,
                              container: ViewGroup?,
                              savedInstanceState: Bundle?): View {
//这里有点问题，改成mRootView = inflater.inflate(layoutId, container, false)就好了，具体原因未知
        mRootView = LayoutInflater.from(context).inflate(layoutId, container, false)
        return mRootView!!
    }

    override fun onDestroyView() {
        super.onDestroyView()
        mRootView = null
    }
}

**Comment by qingmei2** [comment]
@7-cat 

根据你的描述，我不是很清楚，请问遇到了什么问题吗？

**Comment by 7-cat** [comment]
抱歉，本来打算把具体的报错贴出来的，可是今天又不能重现这个问题了。。估计是fragment嵌套或者什么问题引起的。准备移步到MVI-Rhine，感谢你开源这么好的代码，学到了很多。

**Comment by qingmei2** [comment]
@7-cat 

你没有错，直接使用型参中的`inflater`才是正确的使用方式。

从原理上讲，这两种方式获取的`LayoutInflater`对象是不一样的，抽空我研究一下源码，仔细看看差异性在哪里。
