### ISSUE TITLE
RepoPagedViewHolder里面的clickSubject会导致一次点击事件多次触发parentSubject

### ISSUE THREAD

**Issue by 7-cat** [qingmei2/MVVM-Architecture#22]
class RepoPagedViewHolder(private val view: View) : AutoDisposeViewHolder(view) {

    private val clickSubject: PublishSubject<String> = PublishSubject.create()

从room中加载item到recyclerview，然后点击事件触发修改这个item，会重复创建clickSubject

**Comment by qingmei2** [comment]
@7-cat 

谢谢，我这两天检查一下代码

**Comment by qingmei2** [comment]
@7-cat 

没有很理解你的意思，但是仔细检查了一下代码，简单进行了一些调整

**Comment by 7-cat** [comment]
嗯嗯，看了下你修改的代码，是将parentSubject传递到ViewHolder的binds方法中，移除clickSubject，我要表达的也是这个意思。：）
