### ISSUE TITLE
把逻辑都放在fragment中有什么优势吗？

### ISSUE THREAD

**Issue by taozhixiang** [qingmei2/MVVM-Architecture#29]
我看到项目里面所有的内容都写在了fragment中。就是登陆页面也是在activity中嵌套一个fragment。这么做事为什么呢？优势表现在哪些地方呢？

**Comment by qingmei2** [comment]
@taozhixiang 

暂时没有很大的优势，我这样做的考虑可能是将来为 单Activity+多Fragment做准备，所有UI和业务逻辑都委托给Fragment，避免到时候的代码抽取，而Activity尽量只做一些导航类的行为。

**Comment by qingmei2** [comment]
Navigation是一个不错的库，是否尝试应用到正式的生产环境我其实还在观望中哈。
