### ISSUE TITLE
android4.4无法请求数据

### ISSUE THREAD

**Issue by shijunhong** [qingmei2/MVVM-Architecture#31]
Https是Api16开始支持，Api20默认支持。Api19还需要处理下，搞个SSLSocketFactory才行

**Comment by qingmei2** [comment]
最新的代码已提交，由于版本适配不是这个repo的主要功能，因此不针对该bug进行修复了哈。

最新的更新日志参考 [这里](https://github.com/qingmei2/MVVM-Architecture/issues/15)
