### ISSUE TITLE
android4.4 Me页面无法显示头像

### ISSUE THREAD

**Issue by shijunhong** [qingmei2/MVVM-Architecture#32]
`Could not find class 'de.hdodenhof.circleimageview.CircleImageView$OutlineProvider', referenced from method de.hdodenhof.circleimageview.CircleImageView.init
`
circleimageview这个库出的问题，我看了下这个库的issue  https://github.com/hdodenhof/CircleImageView/issues/260
叽里呱啦说了一大堆看的不是很明白，不过看到了把版本改成2.1，现在这个项目是用的2.2的，我尝试修改了下，就显示了。

**Comment by qingmei2** [comment]
@shijunhong 

谢谢你的反馈，请问你有兴趣提PR吗 😄

**Comment by qingmei2** [comment]
最新的代码已提交，由于版本适配不是这个repo的主要功能，因此不针对该bug进行修复了哈。

最新的更新日志参考 [这里](https://github.com/qingmei2/MVVM-Architecture/issues/15)
