### ISSUE TITLE
sharedpref读取问题

### ISSUE THREAD

**Issue by aowoWolf** [qingmei2/MVVM-Architecture#35]
想问一下，你把所有的sharedpref都放在了本地的userRepository中，如果其他类想读写这个sharepref的属性，但是这个类又没传入context对象，在不直接调用sharedpref的方法和实现kodein提供的接口情况下，有什么优雅的方法调用你userRepository中的属性？

**Comment by qingmei2** [comment]
userRepository中的属性大部分场景应该是不可见的，关于sharePref的读写问题，通过一个公共的repository来暴露接口，就好像ServiceManager一样，所有对sharePref的读都通过这个公共的repository进行操作
