### ISSUE TITLE
无网络情况下请求接口闪退

### ISSUE THREAD

**Issue by SnowyTomorrow** [qingmei2/MVVM-Architecture#37]

**Comment by DaQinShgy** [comment]
这是因为协程方式请求没有捕获OkHttp抛出的异常，改造processApiResponse方法，将函数作为参数传入，如下：
suspend fun <T> processResponse(request: suspend () -> Response<T>): Results<T> {
    return try {
        val response = request()
        val responseCode = response.code()
        val responseMessage = response.message()
        if (response.isSuccessful) {
            Results.success(response.body()!!)
        } else {
            loge { "else:" + responseMessage }
            Results.failure(Errors.NetworkError(responseCode, responseMessage))
        }
    } catch (e: IOException) {
        loge { "catch:" + e.toString() }
        Results.failure(Errors.NetworkError())
    }
}

**Comment by BigBigDeBoy** [comment]
这个具体应该怎么改动，上面的代码放在哪里，方便加你联系方式咨询你吗 @DaQinShgy

**Comment by madreain** [comment]
欢迎使用 https://github.com/madreain/AACHulk，并提出相关问题

**Comment by DaQinShgy** [comment]
> 这个具体应该怎么改动，上面的代码放在哪里，方便加你联系方式咨询你吗 @DaQinShgy

用项目中的登录举例：
val userInfoResponse = serviceManager.userService.fetchUserOwner()
processApiResponse(userInfoResponse)

processApiResponse方法中虽然有try catch，但如果serviceManager.userService.fetchUserOwner异常，比如timeout，这个时候是无法捕获的，导致app崩溃。改造processApiResponse方法，将函数作为参数传入，就可以避免这个问题，很多时候使用这个项目崩溃就是因为这个原因引起的
processApiResponse{
     serviceManager.userService.fetchUserOwner()
}

**Comment by qingmei2** [comment]
@DaQinShgy 

谢谢你指出了项目中的问题，正确的方式的确是「将函数作为参数交给processApiResponse」，这样网络请求的行为导致的异常就能够被 `processApiResponse` 函数中 `try catch` 捕获到。

很抱歉问题拖了很久，目前最新的代码已经修复，再次感谢。
