### ISSUE TITLE
net error

### ISSUE THREAD

**Issue by silentpride** [qingmei2/MVVM-Architecture#4]
登录成功，然后404 err

**Comment by qingmei2** [comment]
@silentpride 你好

我不是很清楚这个404和login有没有关系，因为Github的API Json格式我是从postman上跑自己的数据写的，因此不同的用户数据不同，可能会导致格式出错或者请求出错。

如有可能，能提供更详细的log吗？

**Comment by Yuelinghui** [comment]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter username
        at com.qingmei2.sample.ui.main.home.HomeRepository.queryReceivedEvents(Unknown Source:40)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.queryReceivedEventsAction(HomeViewModel.kt:82)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.queryReceivedEventsRefreshAction(HomeViewModel.kt:93)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.access$queryReceivedEventsRefreshAction(HomeViewModel.kt:26)
        at com.qingmei2.sample.ui.main.home.HomeViewModel$initReceivedEvents$1.invoke(HomeViewModel.kt:64)
        at com.qingmei2.sample.ui.main.home.HomeViewModel$initReceivedEvents$1.invoke(HomeViewModel.kt:26)
        at com.qingmei2.rhine.adapter.CommonLoadMoreDataSource.loadDataSourceInternal(CommonLoadMoreDataSource.kt:33)
        at com.qingmei2.rhine.adapter.CommonLoadMoreDataSource.loadInitial(CommonLoadMoreDataSource.kt:15)
        at android.arch.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:323)
        at android.arch.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:102)

**Comment by Yuelinghui** [comment]
登录成功了，但是崩溃了，应该是不可空变量赋值null

**Comment by qingmei2** [comment]
@Yuelinghui  

谢谢你的反馈，我将会修复这个问题，也欢迎你们的PR 🤝

**Comment by DymanZy** [comment]
login之后遇到403了

**Comment by MeteorStart** [comment]
我也遇到了这个问题，登录成功之后就崩溃了
` java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter username
        at com.qingmei2.sample.ui.main.home.HomeRepository.queryReceivedEvents(HomeDataSource.kt)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.queryReceivedEventsAction(HomeViewModel.kt:82)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.queryReceivedEventsRefreshAction(HomeViewModel.kt:94)
        at com.qingmei2.sample.ui.main.home.HomeViewModel.access$queryReceivedEventsRefreshAction(HomeViewModel.kt:26)
        at com.qingmei2.sample.ui.main.home.HomeViewModel$initReceivedEvents$1.invoke(HomeViewModel.kt:64)
        at com.qingmei2.sample.ui.main.home.HomeViewModel$initReceivedEvents$1.invoke(HomeViewModel.kt:26)
        at com.qingmei2.rhine.adapter.CommonLoadMoreDataSource.loadDataSourceInternal(CommonLoadMoreDataSource.kt:33)
        at com.qingmei2.rhine.adapter.CommonLoadMoreDataSource.loadInitial(CommonLoadMoreDataSource.kt:15)
        at android.arch.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:323)
        at android.arch.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:102)
        at android.arch.paging.PagedList.create(PagedList.java:190)
        at android.arch.paging.PagedList.access$000(PagedList.java:114)
        at android.arch.paging.PagedList$Builder.build(PagedList.java:362)
        at android.arch.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:201)
        at android.arch.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:166)
        at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by sjqnice** [comment]
404 

11-26 16:27:45.993 5672-5879/com.qingmei2.sample D/OkHttp: --> GET https://api.github.com/users/Jason%20sun/received_events?&page=1&per_page=15
11-26 16:27:45.993 5672-5879/com.qingmei2.sample D/OkHttp: --> END GET
11-26 16:27:46.069 5672-5672/com.qingmei2.sample W/art: Before Android 4.1, method int android.support.v7.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
11-26 16:27:46.167 5672-5942/com.qingmei2.sample D/OkHttp: --> GET https://api.github.com/users/Jason%20sun/repos?&page=1&per_page=15&sort=full_name
11-26 16:27:46.167 5672-5942/com.qingmei2.sample D/OkHttp: --> END GET
11-26 16:27:46.305 5672-5672/com.qingmei2.sample W/Glide: Load failed for null with size [0x0]
    class com.bumptech.glide.load.engine.GlideException: Received null model
11-26 16:27:46.385 5672-5672/com.qingmei2.sample I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
11-26 16:27:46.412 5672-5672/com.qingmei2.sample W/Glide: Load failed for null with size [0x0]
    class com.bumptech.glide.load.engine.GlideException: Received null model
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: <-- 404 Not Found https://api.github.com/users/Jason%20sun/received_events?&page=1&per_page=15 (1219ms)
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: Date: Mon, 26 Nov 2018 08:27:42 GMT
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: Content-Type: application/json; charset=utf-8
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: Transfer-Encoding: chunked
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: Server: GitHub.com
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: Status: 404 Not Found
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: X-RateLimit-Limit: 60
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: X-RateLimit-Remaining: 55
11-26 16:27:47.213 5672-5879/com.qingmei2.sample D/OkHttp: X-RateLimit-Reset: 1543222853
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: X-GitHub-Media-Type: github.v3; format=json
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: Access-Control-Allow-Origin: *
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: X-Frame-Options: deny
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: X-Content-Type-Options: nosniff
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: X-XSS-Protection: 1; mode=block
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: Content-Security-Policy: default-src 'none'
11-26 16:27:47.214 5672-5879/com.qingmei2.sample D/OkHttp: X-GitHub-Request-Id: D8A8:2AE5:958D2A:C81A61:5BFBAE7D
11-26 16:27:47.218 5672-5879/com.qingmei2.sample D/OkHttp: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received"}
11-26 16:27:47.218 5672-5879/com.qingmei2.sample D/OkHttp: <-- END HTTP (131-byte body)
11-26 16:27:47.254 5672-5672/com.qingmei2.sample I/Toast: Show toast from OpPackageName:com.qingmei2.sample, PackageName:com.qingmei2.sample
11-26 16:27:47.307 5672-5942/com.qingmei2.sample D/OkHttp: <-- 404 Not Found https://api.github.com/users/Jason%20sun/repos?&page=1&per_page=15&sort=full_name (1140ms)
11-26 16:27:47.307 5672-5942/com.qingmei2.sample D/OkHttp: Date: Mon, 26 Nov 2018 08:27:42 GMT
11-26 16:27:47.307 5672-5942/com.qingmei2.sample D/OkHttp: Content-Type: application/json; charset=utf-8
11-26 16:27:47.307 5672-5942/com.qingmei2.sample D/OkHttp: Transfer-Encoding: chunked
11-26 16:27:47.307 5672-5942/com.qingmei2.sample D/OkHttp: Server: GitHub.com
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Status: 404 Not Found
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-RateLimit-Limit: 60
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-RateLimit-Remaining: 54
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-RateLimit-Reset: 1543222853
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-GitHub-Media-Type: github.v3; format=json
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Access-Control-Allow-Origin: *
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-Frame-Options: deny
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-Content-Type-Options: nosniff
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-XSS-Protection: 1; mode=block
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: Content-Security-Policy: default-src 'none'
11-26 16:27:47.308 5672-5942/com.qingmei2.sample D/OkHttp: X-GitHub-Request-Id: AD43:7A2F:983CD:DAF93:5BFBAE7D
11-26 16:27:47.309 5672-5942/com.qingmei2.sample D/OkHttp: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#list-user-repositories"}
11-26 16:27:47.309 5672-5942/com.qingmei2.sample D/OkHttp: <-- END HTTP (107-byte body)

**Comment by qingmei2** [comment]
@Yuelinghui 
@MeteorStart 

因为没有成功复现该情况，个人猜测是Github home首页对于ReceivedEvents这个API，EventType我没有写全，导致少许Event字符串不能被成功的被Gson解析，我已经在最新的提交中参照Github的API进行了补全,参考：

d256b0f

**Comment by gaoyl87** [comment]
GET https://api.github.com/users/FreedomCoderELong/repos?&page=1&per_page=15&sort=full_name
D/OkHttp: --> END GET
D/OkHttp: <-- 404 Not Found https://api.github.com/users/FreedomCoderELong/repos?&page=1&per_page=15&sort=full_name (1248ms)
D/OkHttp: Date: Wed, 28 Nov 2018 14:49:23 GMT
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Transfer-Encoding: chunked
D/OkHttp: Server: GitHub.com
D/OkHttp: Status: 404 Not Found
D/OkHttp: X-RateLimit-Limit: 60
D/OkHttp: X-RateLimit-Remaining: 37
D/OkHttp: X-RateLimit-Reset: 1543416893
D/OkHttp: X-GitHub-Media-Type: github.v3; format=json
D/OkHttp: Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
D/OkHttp: Access-Control-Allow-Origin: *
D/OkHttp: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
D/OkHttp: X-Frame-Options: deny
D/OkHttp: X-Content-Type-Options: nosniff
D/OkHttp: X-XSS-Protection: 1; mode=block
D/OkHttp: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
D/OkHttp: Content-Security-Policy: default-src 'none'
D/OkHttp: X-GitHub-Request-Id: 59FA:1D62:1575247:1CFC536:5BFEAAD3
D/OkHttp: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#list-user-repositories"}
D/OkHttp: <-- END HTTP (107-byte body)


项目跑起来会报404；但是在POSTMAN上是能请求到数据的。估计是有什么请求参数，博主没加上去，POSTMAN是直接在cookie里取了。

**Comment by qingmei2** [comment]
@13588823551 

我猜我知道错误发生的原因了，应该是我把参数需要的username传成了nickname....

正确的api：

https://api.github.com/users/13588823551/repos?&page=1&per_page=15&sort=full_name

而不应该是：

https://api.github.com/users/FreedomCoderELong/repos?&page=1&per_page=15&sort=full_name 

犯了个低级的错误，我会很快修复并提交😂
