### ISSUE TITLE
可以加入开发行列一起丰富这个框架吗

### ISSUE THREAD

**Issue by DaQinShgy** [qingmei2/MVVM-Architecture#42]
使用了一段时间之后，觉得这个框架还可以更丰富点，在实际使用过程中情况更复杂，比如不用room的情况，常见的场景就是搜索列表；还有点赞等更新item的功能；上拉加载更多效果、list为空的情况。

**Comment by qingmei2** [comment]
@DaQinShgy 

可以呀，非常欢迎 🎉

**Comment by DaQinShgy** [comment]
多谢，可以加个联系方式吗，我的vx：zhangyu596124864
