### ISSUE TITLE
master分支代码爆红

### ISSUE THREAD

**Issue by walorwang** [qingmei2/MVVM-Architecture#43]
库主能否更严谨些，主分支代码变更后，爆红不能接受吧

**Comment by qingmei2** [comment]
@walorwang

你说的对，AS本地环境出了点问题, 实在抱歉

**Comment by walorwang** [comment]
> @walorwang
> 
> 你说的对，AS本地环境出了点问题, 实在抱歉

非常感谢库主的及时响应和解决问题
