### ISSUE TITLE
登录返回401，Unauthorized

### ISSUE THREAD

**Issue by vscode-as** [qingmei2/MVVM-Architecture#49]
1、已参考README，注册OAuth Application，并在根目录的local.properties文件中填写CLIENT_ID 、CLIENT_SECRET
2、输入有效的github账号密码，登录失败，提示：network failure
3、断点返回错误信息如下：
Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://api.github.com/authorizations}

**Comment by qingmei2** [comment]
是Github登录API升级了，需要升级下版本，这两天我迁移下

{
  "message": "Bad credentials. The API can't be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens",
  "documentation_url": "https://docs.github.com/articles/creating-a-personal-access-token-for-the-command-line"
}

**Comment by qingmei2** [comment]
已修复，请更新最新的代码
