### ISSUE TITLE
com.google.protobuf plugin找不到的问题

### ISSUE THREAD

**Issue by malimalihome** [qingmei2/MVVM-Architecture#51]
sync 结果提示：

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\StudioProjects\MVVM-Architecture\app\build.gradle' line: 8

* What went wrong:
Plugin [id: 'com.google.protobuf', version: '0.8.12'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.google.protobuf:com.google.protobuf.gradle.plugin:0.8.12')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by qingmei2** [comment]
这个依赖是 protobuf 的依赖，正常的网络环境应该是能够下载的，请参考README再检查一下代码配置呢
