### ISSUE TITLE
关于gradle的插件 versionPlugin

### ISSUE THREAD

**Issue by tang5011235** [qingmei2/MVVM-Architecture#57]
我把 你的versionPlugin移植到新的项目中  但是 我无法引用  内部的变量 
而且我每次导入 import com.github.qingmei2.plugin.*  到 build.gradle 文件里面，每次都会被gradle自动删除  ，我已经被搞得遍体鳞伤了 ，求大佬救救

**Comment by qingmei2** [comment]
@tang5011235 

这个 `com.github.qingmei2.plugin.*` 是根据自己项目中 versionPlugin 的 包名自己生成的

将这个包名，改成你项目模块自己的包名试试

**Comment by tang5011235** [comment]
更换了  kotlin + buildSrc   解决了这个问题  ， 感觉这个项目  看着其实比较简单 ，但是内部的思想 是越品越香

**Comment by tang5011235** [comment]
觉得  这个buildSrc 和  gradle plugin的没有升级提示 是一个缺点  ，其他的还是比gradle文件舒服
