### ISSUE TITLE
个人觉得一些好的和不好的

### ISSUE THREAD

**Issue by joker-fu** [qingmei2/MVVM-Architecture#6]
居然git主还有一面之缘，4月我去心田花开面试的时。下载了项目下来看了login和home 2块，开始看着一脸懵逼，跟着文章补了点kodein，然后明朗了许多，很多地方都值得学习。
好的：
1 对kotlin和r'x'java运用确实比较熟练
2 对jetpack组件使用也很好
不好的：
1 一登陆就崩溃了，还有几个地方
2 项目分得太细了特别是配合上databinding kodein arrow 然后再加上 rxjava kotlin一搅和，在实际生产环境难以调试和维护，当人员流动比较大的时候更为突出

**Comment by qingmei2** [comment]
@joker-fu 

你好，感谢你的回复！

> 一登陆就崩溃了，还有几个地方

这些应该是代码的bug，请问能否在下次崩溃时提供对应的log呢～

> 实际生产环境难以调试和维护

我司最新的项目的技术选型，最终使用了该框架（其实之前的项目是Java+MVP，我也是9月份才入职 😄 ），对于代码的复杂性这一点确实如此，实际上，在实际开发中，对于复杂的界面，我也是建议使用 **MVPVM** ——这一点google也是这样建议的，对于非常复杂的业务逻辑，可以为View层增加一个内部类的Presenter层进行状态的辅助维护。

至于代码的可维护性，这个只能说——唯手熟尔2333 ，因为是按照自己的习惯搭建的项目，所以个人用起来还算顺手，如果用于生产环境，完全可以按照自己的风格和爱好（还有实际业务的需求～）增加或者删除对应的库 😄（比如您所说的，Arrow和Kodein，它们本身确实代表着额外的学习成本）。

因为只是一个demo示例，因此我尽量让这个demo精益求精（有朋友说我有点强迫症，我倒是不抵触这种说法哈哈），而不是一昧的扩展页面和功能，**因此也非常欢迎对这个demo提出PR**，这也正像工作中的项目一样，慢慢迭代，慢慢维护，最终才会让产品更完美。

**Comment by qingmei2** [comment]
没有回复，我先关闭了哈
