### ISSUE TITLE
大佬我写的列表库和网络请求完美支持MVVM给我个友链如何

### ISSUE THREAD

**Issue by liangjingkanji** [qingmei2/MVVM-Architecture#60]
[Net](https://github.com/liangjingkanji/Net/): 协程并发网络请求
[BRV](https://github.com/liangjingkanji/BRV/): 快速构建MVVM列表

文档详细DEMO简单

**Comment by qingmei2** [comment]
东哥出品还是靠谱的

**Comment by liangjingkanji** [comment]
多谢哦
