### ISSUE TITLE
首页列表,点击item 崩溃 , 建议修复

### ISSUE THREAD

**Issue by budaowengd** [qingmei2/MVVM-Architecture#7]
点击Home列表的item ,闪退, 
错误如图:
<img width="701" alt="_20181214175741" src="https://user-images.githubusercontent.com/16216657/49996427-e88f1280-ffc9-11e8-990d-72d0bdc72bc1.png">

**Comment by qingmei2** [comment]
@luoxiong94 

谢谢，我稍后会修复它
