### ISSUE TITLE
这个框架太棒了,都是很新的技术

### ISSUE THREAD

**Issue by AmioLee** [qingmei2/MVVM-Architecture#8]
但是对还没学过kotlin的我，看到一脸懵逼，甚至不知道如何在application里面使用项目中的PrefsHelper，
请问这个框架可以用到正式项目中吗？后续是否在维护。
如果用java写的估计star 至少x10了现在。

**Comment by qingmei2** [comment]
谢谢你的支持，目前我司项目使用的基于这个repo进行开发的，完全可以用于正式项目。

> 后续是否在维护

欢迎各位提出宝贵的意见，我会 **持续关注并长期保证更新**。

**Comment by 13kmsteady** [comment]
@AmioLee 我也在项目中使用了。2 个月前我和你一样，到处懵逼.jpg，写的这都是啥玩意。由于我朋友极力推荐这个库，我便下定决心学习。

简单说下我的学习历程：
1. **Kotlin** 知识，掌握基本的语法，能大概看明白
2. **DataBinding** 知识，掌握用法
3. **Jetpack** 组件的使用，如：**Lifecycle**，**ViewModel**，**LiveData**
4. **Kodein** 依赖注入，如果有 **Dagger2** 知识，上手很快
5. 剩下的就是跟着代码敲，一定要多敲，我当初敲完以后，觉得这代码写的是真心漂亮。

其实上面提到的这些东西，通过较短的时间。都可以上手。但是作者对于 **RxJava** 的运用，是我认为比较难的一点，**Rx** 的思想也不是一蹴而就的，这个急不得。并且 **MVVM** 的开发模式在移动端越来越普及，这个项目是很好的学习机会。

这些技术，作者都通过博客记录了，可以很快的入门。相信你也可以掌握的，加油！

**Comment by qingmei2** [comment]
@AmioLee @13kmsteady 

如果没有问题，我就先关闭issue了 😄

**Comment by MhuiHugh** [comment]
Hi,Demo中minSdkVersion  : 19 能否支持到15-Android4.0.3系统？

**Comment by qingmei2** [comment]
@MhuiHugh 

可以
