### ISSUE TITLE
Use abstract instead of open modfier

### ISSUE THREAD

**Issue by igorwojda** [qingmei2/MVVM-Architecture#9]
https://github.com/qingmei2/MVVM-Rhine/blob/9b408036eb73c013736b35668b90053f64fa050d/rhine/src/main/java/com/qingmei2/rhine/base/view/activity/InjectionActivity.kt#L12

I think `abstract` modifier would be better suited here and in the `BaseActivity` and `AutoDisposeActivity`

**Comment by qingmei2** [comment]
@igorwojda 

Yes, that would be better 👍 I will make changes when I am free 😄 .

**Comment by qingmei2** [comment]
Thank you for reminding me, the code has been modified:

a9c2b12
